[project]
authors = ["Silvio Travesaro <silvio.traversaro@iit.it>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "ompl"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
build = { cmd = "cmake -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=ON -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING:BOOL=ON -DCMAKE_INSTALL_PREFIX=./install -GNinja -S. -Bbuild  && cmake --build build --config Release" }
test = { cmd = "ctest --output-on-failure", cwd = "build", depends_on = [
    "build",
] }

[dependencies]
compilers = ">=1.8.0,<2"
cmake = ">=3.31.1,<4"
pkg-config = ">=0.29.2,<0.30"
eigen = ">=3.4.0,<4"
make = ">=4.4.1,<5"
ninja = ">=1.12.1,<2"
libboost-devel = ">=1.86.0,<2"
